### ISSUE TITLE
problems with modal backdrop z-index on various skins

### ISSUE THREAD

**Issue by oetterer** [cmln/mw-bootstrap#7]
Hi @s7eph4n 

Since mw skins often rely on positioning and z-index, things sometimes get messy [0]. When using bootstrap modals for example, the backdrop is added by javascript at the very end of the body tag. Which in turn causes the backdrop to actually overlay the modal, including the close button. A workround so far was to disable the backdrop, which does the trick but produces a modal that does not quite behave like a bootstrap modal. A fix for mw skins is to add the backdrop to the #content element instead of the body tag. This can be done easily with

```
diff --git a/resources/bootstrap/js/modal.js b/resources/bootstrap/js/modal.js
index f84142d..237f64d 100644
--- a/resources/bootstrap/js/modal.js
+++ b/resources/bootstrap/js/modal.js
@@ -15,7 +15,7 @@

   var Modal = function (element, options) {
     this.options             = options
-    this.$body               = $(document.body)
+    this.$body               = $(' #content' )
     this.$element            = $(element)
     this.$dialog             = this.$element.find('.modal-dialog')
     this.$backdrop           = null
```
However, since the bootstrap javascript is an external resource, I was wondering if there is an alternative to that. Or do you see a possibility to integrate this change in your extension?

Cheer,
Tobi

[0] https://philipwalton.com/articles/what-no-one-told-you-about-z-index/

**Comment by s7eph4n** [comment]
Hi Tobi.

I don't have an easy solution, just some thoughts for the moment.

I think the developers are aware of that limitation. See the "Modal markup placement" remark at https://getbootstrap.com/docs/3.3/javascript/#modals
I wonder if there is a respective upstream bug, but even if so, with Bootstrap 4 being out it might be obsolete.
This extension, too, is about to get a new major version soonish using Bootstrap 4.
An alternative to your solution might be to use some JavaScript to take the modal out of the document flow and move it to the top level. But that might lead to other problems, e.g. event handlers expecting the modal to be at a certain position in the document.
Using `#content` usually does not cover the menu and similar UI elements, i.e. the modal would not really be modal anymore.
`#content` may not be used by every skin.
Since about a year Bootstrap is delivered directly with the extension and not pulled in with Composer anymore. See 73c3158750605ac88dd6f715aa49a559d43b754f.

**Comment by oetterer** [comment]
Hey Stephan

thanks for your thoughts and your input. I will work with my patch on my systems for the time being and wait for bootstrap4. Lets see, what they will cook up. :)

Cheers
